language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=3.1.3
install:
  - sudo apt-get install sqlcipher
  - sudo apt-get install libsqlcipher-dev
  - pip install -r requirements.txt
script:
  - cd assignment2
  - python manage.py test < "input.txt"
