apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-1606493721
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-11-27T16:15:27Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-12.0.1
    component: alertmanager
    heritage: Helm
    release: prometheus-1606493721
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:alertmanager.yml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
    manager: Go-http-client
    operation: Update
    time: "2020-11-27T16:15:27Z"
  name: prometheus-1606493721-alertmanager
  namespace: default
  resourceVersion: "89896"
  selfLink: /api/v1/namespaces/default/configmaps/prometheus-1606493721-alertmanager
  uid: 5bebab35-e49e-4844-998b-c346218bdb27
