giftcardreader: giftcardreader.c
	gcc -o ./build/giftcardreader giftcardreader.c && ./build/giftcardreader 1 examplefile.gft


giftcardexamplewriter: 
	gcc -o ./build/giftcardexamplewriter giftcardexamplewriter.c && ./build/giftcardexamplewriter


