apiVersion: batch/v1
kind: Job
metadata:
  name: assignment3-django-migrations
spec:
  template:
    spec:
      containers:
        - name: assignment3-django-migrations
          image: nyuappsec/assign3:v2
          
          command: ["/bin/sh", "-c"]
          args: ["python manage.py makemigrations; python manage.py migrate"]
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: root-password

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: database

            - name: MYSQL_HOST
              value: mysql-service

            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: django-generic
                  key: allowed-hosts

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                    name: django-generic
                    key: secret-key

            - name: RANDOM_SEED
              valueFrom:
                secretKeyRef:
                    name: django-generic
                    key: random-seed

      restartPolicy: Never

